# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u7c7b\u522b\u540d\u79f0')),
                ('isIncome', models.BooleanField(choices=[(True, '\u6536\u5165'), (False, '\u652f\u51fa')], verbose_name='\u662f\u5426\u6536\u5165')),
                ('p_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='jizhang.Category', verbose_name='\u7236\u7c7b\u540d\u79f0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6240\u5c5e\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='\u91d1\u989d')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='\u6ce8\u91ca')),
                ('pub_date', models.DateField(verbose_name='\u65e5\u671f')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jizhang.Category', verbose_name='\u5206\u7c7b')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
